spring:
  profiles:
    include: @env@

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    cache-enabled: false
    local-cache-scope: statement